/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import AppLogic.iReportView;
import AppLogic.logicAddCategories;
import Source.Validation;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanuka Perera
 */
public class AddCategories extends javax.swing.JPanel {

         logicAddCategories newCategory = new logicAddCategories();
    /**
     * Creates new form AddCategories
     */
    public AddCategories() {
        initComponents();
        newCategory.tableLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appBackground = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReports = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAddCategories = new javax.swing.JTable();
        cmbFilter = new javax.swing.JComboBox<>();
        lblFindIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtFind = new javax.swing.JTextField();

        appBackground.setBackground(new java.awt.Color(51, 51, 51));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpdateMouseReleased(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteMouseReleased(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear2.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/reports.png"))); // NOI18N
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Category");

        txtCategory.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtCategory.setForeground(new java.awt.Color(51, 51, 51));
        txtCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jScrollPane2.setViewportView(txtDescription);

        jLabel2.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Description");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategory)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblAddCategories.setBackground(new java.awt.Color(51, 51, 51));
        tblAddCategories.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        tblAddCategories.setForeground(new java.awt.Color(255, 255, 255));
        tblAddCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAddCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAddCategoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAddCategories);

        cmbFilter.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbFilter.setForeground(new java.awt.Color(51, 51, 51));
        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Category ID", "Category", "Description" }));

        lblFindIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/touch.png"))); // NOI18N
        lblFindIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFindIconMouseClicked(evt);
            }
        });

        txtFind.setFont(new java.awt.Font("Myriad Web Pro", 2, 14)); // NOI18N
        txtFind.setForeground(new java.awt.Color(255, 255, 255));
        txtFind.setText("Find...");
        txtFind.setBorder(null);
        txtFind.setOpaque(false);
        txtFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFindMouseClicked(evt);
            }
        });
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout appBackgroundLayout = new javax.swing.GroupLayout(appBackground);
        appBackground.setLayout(appBackgroundLayout);
        appBackgroundLayout.setHorizontalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, appBackgroundLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReports)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appBackgroundLayout.createSequentialGroup()
                                .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFindIcon)
                                .addGap(6, 6, 6)
                                .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        appBackgroundLayout.setVerticalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(appBackgroundLayout.createSequentialGroup()
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFindIcon)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered

        try {

            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/add_hover.png"));
            btnAdd.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited

        try {

            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/add.png"));
            btnAdd.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        
        
    }//GEN-LAST:event_btnAddMouseReleased

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit_hover.png"));
            btnUpdate.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit.png"));
            btnUpdate.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnUpdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseReleased

       

    }//GEN-LAST:event_btnUpdateMouseReleased

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete_hover.png"));
            btnDelete.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete.png"));
            btnDelete.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseReleased

        
    }//GEN-LAST:event_btnDeleteMouseReleased

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2_hover.png"));
            btnClear.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2.png"));
            btnClear.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseClicked
         iReportView r = new iReportView( Main.path+ "\\src\\Reports\\AddCategory.jasper");
        r.setVisible(true);
        

    }//GEN-LAST:event_btnReportsMouseClicked

    private void btnReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseEntered
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports_hover.png"));
            btnReports.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnReportsMouseEntered

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        try
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports.png"));
            btnReports.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnReportsMouseExited

    private void lblFindIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFindIconMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblFindIconMouseClicked

    private void txtFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFindMouseClicked
        txtFind.setText("");
    }//GEN-LAST:event_txtFindMouseClicked

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed

        //newCDDVDs.find(cmbCatorgies.getSelectedItem().toString(), txtFind.getText());
        newCategory.find(cmbFilter.getSelectedItem().toString(), txtFind.getText());
        try {

            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/touch_hover.png"));
            lblFindIcon.setIcon(changeIcon);

        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_txtFindKeyPressed

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        newCategory.find(cmbFilter.getSelectedItem().toString(), txtFind.getText());
    }//GEN-LAST:event_txtFindKeyReleased

    private void tblAddCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAddCategoriesMouseClicked

        int getSelectedRow = tblAddCategories.getSelectedRow();

       
        String Category= tblAddCategories.getValueAt(getSelectedRow, 1).toString();
        String Description= tblAddCategories.getValueAt(getSelectedRow, 2).toString();
          

        txtCategory.setText(Category);
        txtDescription.setText(Description);
        
        

    }//GEN-LAST:event_tblAddCategoriesMouseClicked

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       
          if((Validation.isEmpty(txtCategory.getText())==false)&&(Validation.isEmpty(txtDescription.getText()))==false)     
        {
            newCategory.Add(txtCategory.getText(),txtDescription.getText());
           newCategory.tableLoad();
           
        }      
          else
        {
           JOptionPane.showMessageDialog(null, "Please Fill all the fields","Error",JOptionPane.ERROR_MESSAGE );
           
        }
      
          clear();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
         int msg = JOptionPane.showConfirmDialog(null,"Do you really want to UPDATE this record?");

        if(msg==0){

            int getRowId = tblAddCategories.getSelectedRow();

            String CategoryId = tblAddCategories.getValueAt(getRowId, 0).toString();
             
        if((Validation.isEmpty(txtCategory.getText())==false)&&(Validation.isEmpty(txtDescription.getText()))==false)     
        {
           newCategory.Update(CategoryId,txtCategory.getText(),txtDescription.getText());
           newCategory.tableLoad();
           
        }      
          else
        {
          JOptionPane.showMessageDialog(null, "Please Fill all the fields","Error",JOptionPane.ERROR_MESSAGE );
           
        }
        
        clear();
            
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

        int msg = JOptionPane.showConfirmDialog(null, "Do you really want to DELETE this record?");
        
        if(msg == 0)
        {
              int getRowId = tblAddCategories.getSelectedRow();
        String CategoryId = tblAddCategories.getValueAt(getRowId, 0).toString();
        newCategory.delete(CategoryId);
        
        }
       
        
          clear();
        
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

     public void clear(){
    
        txtCategory.setText("");
        txtDescription.setText("");
        txtFind.setText("");
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appBackground;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReports;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFindIcon;
    public static javax.swing.JTable tblAddCategories;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
