/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import AppLogic.iReportView;
import java.sql.*;
import net.sf.jasperreports.engine.design.*;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.view.JasperDesignViewer;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.*;
import javax.swing.*;
import AppLogic.logicBooks;
import Source.DBConnection;
import Source.Validation;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanuka Perera
 */
public class Books extends javax.swing.JPanel {
    
logicBooks newBook = new logicBooks();
    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
        
        //loading the table and the category Jcombobox
        newBook.tableLoad();
        newBook.LoadCategories();
        
        //Find text is null load the table
        if(txtFind.getText()==null)
            newBook.tableLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appBackground = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtFind = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblFindIcon = new javax.swing.JLabel();
        cmbList = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbCatagory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAuthorname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEdition = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();

        appBackground.setBackground(new java.awt.Color(51, 51, 51));
        appBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                appBackgroundMouseMoved(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear2.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/reports.png"))); // NOI18N
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        txtFind.setFont(new java.awt.Font("Myriad Web Pro", 2, 14)); // NOI18N
        txtFind.setForeground(new java.awt.Color(255, 255, 255));
        txtFind.setText("Find...");
        txtFind.setBorder(null);
        txtFind.setOpaque(false);
        txtFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFindMouseClicked(evt);
            }
        });
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        lblFindIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/touch.png"))); // NOI18N

        cmbList.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbList.setForeground(new java.awt.Color(51, 51, 51));
        cmbList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book ID", "ISBN", "Title", "Category", "Author Name", "Edition", "Quantity" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFindIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFind))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFindIcon))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ISBN");

        txtISBN.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtISBN.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });
        txtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtISBNKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Title");

        txtTitle.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTitleKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Catagory");

        cmbCatagory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCatagory.setName(""); // NOI18N
        cmbCatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCatagoryActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Author name");

        txtAuthorname.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtAuthorname.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtAuthorname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAuthornameKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edition");

        txtEdition.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtEdition.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtEdition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditionKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");

        txtQuantity.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtQuantity.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtAuthorname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(txtISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAuthorname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblBooks.setBackground(new java.awt.Color(51, 51, 51));
        tblBooks.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        tblBooks.setForeground(new java.awt.Color(255, 255, 255));
        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBooks);

        javax.swing.GroupLayout appBackgroundLayout = new javax.swing.GroupLayout(appBackground);
        appBackground.setLayout(appBackgroundLayout);
        appBackgroundLayout.setHorizontalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appBackgroundLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appBackgroundLayout.createSequentialGroup()
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        appBackgroundLayout.setVerticalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReport)
                    .addComponent(btnClear)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    void clear()
    {
        txtISBN.setText("");
        txtTitle.setText("");
        //cmbCatagory
        txtAuthorname.setText("");
        txtEdition.setText("");
        txtQuantity.setText("");
        txtFind.setText("Find...");
    }
    
    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/add_hover.png"));
             btnAdd.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
           
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
          try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/add.png"));
             btnAdd.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnAddMouseExited

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/touch_hover.png"));
             lblFindIcon.setIcon(changeIcon);
             
             
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_txtFindKeyPressed

    private void appBackgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appBackgroundMouseMoved
        //mouse moved away from the find textbox    
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/touch.png"));
             lblFindIcon.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    
    }//GEN-LAST:event_appBackgroundMouseMoved

    private void txtFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFindMouseClicked
      txtFind.setText("");
    }//GEN-LAST:event_txtFindMouseClicked

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void cmbCatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCatagoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCatagoryActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
      
        if((Validation.isEmpty(txtISBN.getText()) == false) && (Validation.isEmpty(txtTitle.getText())==false)&&(Validation.isEmpty(txtAuthorname.getText())==false)&&(Validation.isEmpty(txtEdition.getText())==false)&&(Validation.isEmpty(txtQuantity.getText())==false)&&(Validation.isEmpty(txtQuantity.getText())==false))
        {
            newBook.Add(txtISBN.getText(),txtTitle.getText(),cmbCatagory.getSelectedItem().toString(),txtAuthorname.getText(),txtEdition.getText(),txtQuantity.getText(),txtQuantity.getText());
            newBook.tableLoad();
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Please Fill all the fields","Error",JOptionPane.ERROR_MESSAGE);

        }
        clear();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        
        int msg =  JOptionPane.showConfirmDialog(null,"Do you really want to UPDATE this record?"); 
        
        if(msg ==0 )
        {
            try{
            
        int getSelectedRow = tblBooks.getSelectedRow();
        String BookID = tblBooks.getValueAt(getSelectedRow,0).toString();
       
          if((Validation.isEmpty(txtISBN.getText())== false)&&(Validation.isEmpty(txtTitle.getText())== false)&&(Validation.isEmpty(txtAuthorname.getText())== false)&&(Validation.isEmpty(txtEdition.getText())== false)&&(Validation.isEmpty(txtQuantity.getText())== false)&&(Validation.isEmpty(txtQuantity.getText())== false))
        {
            newBook.updateTable(BookID,txtISBN.getText(),txtTitle.getText(),cmbCatagory.getSelectedItem().toString(),txtAuthorname.getText(),txtEdition.getText(),txtQuantity.getText(),txtQuantity.getText());
            newBook.tableLoad();
        }
          else
        {
            JOptionPane.showMessageDialog(null,"Please Fill all the fields","Error",JOptionPane.ERROR_MESSAGE);
        }
        }
        catch(Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
       clear();
        }
       
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        //Deleting data of the Table
        
          int msg = JOptionPane.showConfirmDialog(null, "Do you really want to DELETE this record?");
          
            if (msg == 0) 
            {
                int getSelectedRow = tblBooks.getSelectedRow();
            String BookID = tblBooks.getValueAt(getSelectedRow,0).toString();
        
                newBook.delete(BookID);
                newBook.tableLoad();
       
                clear();
            }
        
        
      
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        
        clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseClicked
       
       iReportView r = new iReportView( Main.path+ "\\src\\Reports\\BookReport.jasper");
        r.setVisible(true);
        
    }//GEN-LAST:event_btnReportMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit_hover.png"));
             btnUpdate.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete_hover.png"));
             btnDelete.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2_hover.png"));
             btnClear.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports_hover.png"));
             btnReport.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
         try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit.png"));
             btnUpdate.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
         try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete.png"));
             btnDelete.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
         try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2.png"));
             btnClear.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
         try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports.png"));
             btnReport.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnReportMouseExited

    private void tblBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBooksMouseClicked
        int getSelectedRow = tblBooks.getSelectedRow();
        
        String ISBN = tblBooks.getValueAt(getSelectedRow,1).toString();
        String Title = tblBooks.getValueAt(getSelectedRow,2).toString();
        String Category = tblBooks.getValueAt(getSelectedRow,3).toString();
        String AuthorName = tblBooks.getValueAt(getSelectedRow,4).toString();
        String Edition = tblBooks.getValueAt(getSelectedRow,5).toString();
        String Quantity = tblBooks.getValueAt(getSelectedRow,6).toString();
        
        txtISBN.setText(ISBN);
        txtTitle.setText(Title);
        cmbCatagory.setSelectedItem(Category);
        txtAuthorname.setText(AuthorName);
        txtEdition.setText(Edition);
        txtQuantity.setText(Quantity);
    }//GEN-LAST:event_tblBooksMouseClicked

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
            try{ 
        String list = cmbList.getSelectedItem().toString();
             String search = txtFind.getText();
             newBook.find(list,search);
            }
            catch(Exception e)
            {
                //ss
            }
    }//GEN-LAST:event_txtFindKeyReleased

    private void txtEditionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditionKeyReleased
     
        
        if(Validation.validatenumbers(txtEdition.getText()))
        {
           JOptionPane.showMessageDialog(null,"Please Enter a valid number","Error",JOptionPane.ERROR_MESSAGE);
           txtEdition.setText("");
        }
        
    }//GEN-LAST:event_txtEditionKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
         if(Validation.validatenumbers(txtQuantity.getText()))
        {
           JOptionPane.showMessageDialog(null,"Please Enter a valid number","Error",JOptionPane.ERROR_MESSAGE);
           txtQuantity.setText("");
        }
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtISBNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNKeyReleased
        if(Validation.validatenumbers(txtISBN.getText()))
        {
           JOptionPane.showMessageDialog(null,"Please Enter a valid number","Error",JOptionPane.ERROR_MESSAGE);
           txtISBN.setText("");
        }
    }//GEN-LAST:event_txtISBNKeyReleased

    private void txtAuthornameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAuthornameKeyReleased
        if(Validation.validatetext(txtAuthorname.getText()))
        {
           JOptionPane.showMessageDialog(null,"Please Enter a valid name","Error",JOptionPane.ERROR_MESSAGE);
           txtAuthorname.setText("");
        }
    }//GEN-LAST:event_txtAuthornameKeyReleased

    private void txtTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTitleKeyReleased
         if(Validation.validatetext(txtTitle.getText()))
        {
           JOptionPane.showMessageDialog(null,"Please Enter a valid name","Error",JOptionPane.ERROR_MESSAGE);
           txtTitle.setText("");
        }
    }//GEN-LAST:event_txtTitleKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appBackground;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReport;
    private javax.swing.JLabel btnUpdate;
    public static javax.swing.JComboBox<String> cmbCatagory;
    private javax.swing.JComboBox cmbList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFindIcon;
    public static javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtAuthorname;
    public static javax.swing.JTextField txtEdition;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
