/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import AppLogic.LogicHome;
import static Frames.Main.pnlAppLoader;
import Source.Validation;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanuka Perera
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    
    String userId;
      Validation val = new Validation();
     LogicHome newHome = new LogicHome();
    public Home() {
        initComponents();
        txtComfromPassword.setText(txtPassword.getText());
         date_time();
        newHome.loadAdminPfofileData();
         newHome.LoadNotice();
        
        
        txtName.setEnabled(false);
        txtAccountType.setEnabled(false);
        txtAddress.setEnabled(false);
        txtStaffID.setEnabled(false);
        cmbGender.setEnabled(false);
        txtContactNo.setEnabled(false);
        txtEmail.setEnabled(false);
        txtPassword.setEnabled(false);
        txtComfromPassword.setEnabled(false);
        
        txtComfromPassword.setText(txtPassword.getText());
        
        
        try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/profile_admin.png"));
            Home.lblProfile.setIcon(changeIcon);
        } 
        catch (Exception e) 
        {
            
        }
        
        
       // newHome.getData();
      
       // newHome.getData();
    }
    
   
    
    public Home(String id)
    {
        initComponents();
        date_time();
        
        this.userId = id;
        System.out.println("In home: " + id);
        newHome.loadProfileData(this.userId);
        newHome.LoadNotice();
        
        txtName.setEnabled(false);
        txtAccountType.setEnabled(false);
        txtAddress.setEnabled(false);
        txtStaffID.setEnabled(false);
        cmbGender.setEnabled(false);
        txtContactNo.setEnabled(false);
        txtEmail.setEnabled(false);
        txtPassword.setEnabled(false);
        txtComfromPassword.setEnabled(false);
        
        txtComfromPassword.setText(txtPassword.getText());
        
        String gender = cmbGender.getSelectedItem().toString();
        if(gender.equals("Male"))
        {
            try 
            {
                ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/profilepic_male.png"));
                Home.lblProfile.setIcon(changeIcon);
            } 
            catch (Exception e) 
            {
            
            }
        }
        else if(gender.equals("Female"))
        {
            try 
            {
                ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/profilepic_female.png"));
                Home.lblProfile.setIcon(changeIcon);
            } 
            catch (Exception e) 
            {
            
            }
        }
        
        
    }
    
     public final void date_time() {
        java.util.Date date = new java.util.Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd-EEEEE");
        lblTime.setText(sdf.format(date));

        new Thread(() -> {
            while (true) {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat sdf1 = new SimpleDateFormat("hh.mm.ss aa");
                lblDate.setText(sdf1.format(d));
            }
        }).start();
 }
    
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtAccountType = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtComfromPassword = new javax.swing.JPasswordField();
        cmbGender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        bgimg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblNotice = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));

        lblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/profile_admin.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Myriad Web Pro", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Stafff ID");

        jLabel5.setFont(new java.awt.Font("Myriad Web Pro", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Gender");

        txtName.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(44, 62, 80));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setText("Library Management System");
        txtName.setToolTipText("");
        txtName.setBorder(null);
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.setOpaque(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtContactNo.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtContactNo.setForeground(new java.awt.Color(44, 62, 80));
        txtContactNo.setToolTipText("");
        txtContactNo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtContactNo.setOpaque(false);
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactNoKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Myriad Web Pro", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("ContactNo");

        txtEmail.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(44, 62, 80));
        txtEmail.setToolTipText("");
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Myriad Web Pro", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Email");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save_small.png"))); // NOI18N
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit_small.png"))); // NOI18N
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(44, 62, 80));
        txtAddress.setToolTipText("");
        txtAddress.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAddress.setOpaque(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtAccountType.setEditable(false);
        txtAccountType.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtAccountType.setForeground(new java.awt.Color(44, 62, 80));
        txtAccountType.setText("Admin");
        txtAccountType.setToolTipText("");
        txtAccountType.setBorder(null);
        txtAccountType.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAccountType.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Myriad Web Pro", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText("Password");

        jLabel12.setFont(new java.awt.Font("Myriad Web Pro", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(44, 62, 80));
        jLabel12.setText("Conform Password");

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(44, 62, 80));
        txtPassword.setText("jPasswordField1");
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.setOpaque(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtComfromPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtComfromPassword.setForeground(new java.awt.Color(44, 62, 80));
        txtComfromPassword.setText("jPasswordField1");
        txtComfromPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtComfromPassword.setOpaque(false);
        txtComfromPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComfromPasswordActionPerformed(evt);
            }
        });

        cmbGender.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbGender.setForeground(new java.awt.Color(44, 62, 80));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenderActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Myriad Web Pro", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(44, 62, 80));
        jLabel10.setText("Address");

        txtStaffID.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtStaffID.setForeground(new java.awt.Color(44, 62, 80));
        txtStaffID.setToolTipText("");
        txtStaffID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtStaffID.setOpaque(false);
        txtStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave))
                            .addComponent(txtComfromPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContactNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffID))
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfile)
                .addGap(18, 18, 18)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComfromPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bgimg.setBackground(new java.awt.Color(51, 51, 51));
        bgimg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblTime.setFont(new java.awt.Font("Myriad Web Pro", 0, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Date");

        lblDate.setFont(new java.awt.Font("Myriad Web Pro", 0, 40)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate.setText("Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate)
                    .addComponent(lblTime))
                .addGap(0, 134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addContainerGap())
        );

        bgimg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 220, -1));

        lblNotice.setFont(new java.awt.Font("Myriad Web Pro", 0, 18)); // NOI18N
        lblNotice.setForeground(new java.awt.Color(211, 84, 0));
        lblNotice.setText("Notice :");
        bgimg.add(lblNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home_bg.png"))); // NOI18N
        bgimg.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bgimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bgimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtComfromPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComfromPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComfromPasswordActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void cmbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenderActionPerformed

    private void txtStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffIDActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        
        if(txtStaffID.getText().equals("root"))
        {
          //  txtName.setEnabled(true);
       // txtAccountType.setEnabled(true);
      //  txtStaffID.setEnabled(true);
         txtAddress.setEnabled(true);
        cmbGender.setEnabled(true);
        txtContactNo.setEnabled(true);
        txtEmail.setEnabled(true);
        txtPassword.setEnabled(true);
        txtComfromPassword.setEnabled(true); 
        }
        else
        {
            txtName.setEnabled(true);
        txtAccountType.setEnabled(true);
       // txtStaffID.setEnabled(true);
         txtAddress.setEnabled(true);
        cmbGender.setEnabled(true);
        txtContactNo.setEnabled(true);
        txtEmail.setEnabled(true);
        txtPassword.setEnabled(true);
        txtComfromPassword.setEnabled(true); 
        }
        
        
       
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
         try {
              ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit_small_hover.png"));
              btnEdit.setIcon(changeIcon);
        } catch (Exception e) {
            //Error
        }
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
         try {
              ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit_small.png"));
              btnEdit.setIcon(changeIcon);
        } catch (Exception e) {
            //Error
        }
    }//GEN-LAST:event_btnEditMouseExited

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
         try {
              ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/save_small_hover.png"));
              btnSave.setIcon(changeIcon);
        } catch (Exception e) {
            //Error
        }
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
          try {
              ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/save_small.png"));
              btnSave.setIcon(changeIcon);
        } catch (Exception e) {
            //Error
        }
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        
//         if((Validation.isEmpty(txtStaffID.getText())==true)&&(Validation.isEmpty(txtAddress.getText())==true)&&(Validation.isEmpty(txtContactNo.getText())==true)&&(Validation.isEmpty(txtEmail.getText())==true)&&(Validation.isEmpty(txtComfromPassword.getText()))){
//         
//             JOptionPane.showMessageDialog(null,"Please Fill all the fields" ,"Error", JOptionPane.ERROR_MESSAGE);
//         }
//         else if(Validation.emailvalidation(txtEmail.getText())==false){
//             JOptionPane.showMessageDialog(null,"Please Enter a valid email" ,"Error", JOptionPane.ERROR_MESSAGE);
//         
//         }
//         
//         else{
//          if(txtStaffID.getText().equals("root"))
//        {
//            newHome.editAdminProfile(txtAddress.getText(),cmbGender.getSelectedItem().toString(),txtContactNo.getText(), txtEmail.getText(), txtPassword.getText());
//            
//            //txtName.setEnabled(false);
//           // txtAccountType.setEnabled(false);
//            //txtStaffID.setEnabled(false);
//            cmbGender.setEnabled(false);
//            txtContactNo.setEnabled(false);
//            txtAddress.setEnabled(false);
//            txtEmail.setEnabled(false);
//            txtPassword.setEnabled(false);
//            txtComfromPassword.setEnabled(false);
//        }
//        else    
//        {
//            newHome.editProfile(this.userId,txtName.getText(), txtAccountType.getText(), txtAddress.getText(),cmbGender.getSelectedItem().toString(),txtContactNo.getText(), txtEmail.getText(), txtPassword.getText());
//            
//            txtName.setEnabled(false);
//            txtAccountType.setEnabled(false);
//            txtStaffID.setEnabled(false);
//            cmbGender.setEnabled(false);
//            txtContactNo.setEnabled(false);
//            txtAddress.setEnabled(false);
//            txtEmail.setEnabled(false);
//            txtPassword.setEnabled(false);
//            txtComfromPassword.setEnabled(false);
//        }
//         
//         }

      if( (!txtName.getText().equals("")) && (!txtAccountType.getText().equals("")) && (!txtStaffID.getText().equals("")) && (!txtAddress.getText().equals("")) && (!txtContactNo.getText().equals(""))&&(!txtContactNo.getText().equals("")) && (!txtPassword.getText().equals("")) && (!txtComfromPassword.getText().equals("")) )
        {
          
          if(Validation.emailvalidation(txtEmail.getText())==true)
          {
              if(txtPassword.getText().equals(txtComfromPassword.getText()))
              {
                  
                  if(txtStaffID.getText().equals("root"))
                  {
                    int msg =  JOptionPane.showConfirmDialog(null,"Do you really want to UPDATE this record?");
                    
                    if(msg ==0)
                    {
                        newHome.editAdminProfile(txtAddress.getText(),cmbGender.getSelectedItem().toString(),txtContactNo.getText(), txtEmail.getText(), txtPassword.getText());
            
                        txtName.setEnabled(false);
                        txtAccountType.setEnabled(false);
                        txtStaffID.setEnabled(false);
                        cmbGender.setEnabled(false);
                        txtContactNo.setEnabled(false);
                        txtAddress.setEnabled(false);
                        txtEmail.setEnabled(false);
                        txtPassword.setEnabled(false);
                        txtComfromPassword.setEnabled(false); 
                    }

                  }
                  else
                  {
                    int msg =  JOptionPane.showConfirmDialog(null,"Do you really want to UPDATE this record?"); 
                    
                    if(msg==0)
                    {
                        newHome.editProfile(this.userId,txtName.getText(), txtAccountType.getText(), txtAddress.getText(),cmbGender.getSelectedItem().toString(),txtContactNo.getText(), txtEmail.getText(), txtPassword.getText());
            
                        txtName.setEnabled(false);
                        txtAccountType.setEnabled(false);
                        txtStaffID.setEnabled(false);
                        cmbGender.setEnabled(false);
                        txtContactNo.setEnabled(false);
                        txtAddress.setEnabled(false);
                        txtEmail.setEnabled(false);
                        txtPassword.setEnabled(false);
                        txtComfromPassword.setEnabled(false); 
                    }
                      
                  }
              }
              else
              {
                 JOptionPane.showMessageDialog(null,"Password not match" ,"Error", JOptionPane.ERROR_MESSAGE); 
              }
              
          }
          
          else
          {
              JOptionPane.showMessageDialog(null,"Please Enter a valid email" ,"Error", JOptionPane.ERROR_MESSAGE);
          }
      }
      else
      {
          JOptionPane.showMessageDialog(null,"Please Fill all the fields" ,"Error", JOptionPane.ERROR_MESSAGE);
      }
              
          
              
          
       
       
        
        
       
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtContactNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyReleased
        if(Validation.validatenumbers(txtContactNo.getText())){
        JOptionPane.showMessageDialog(null, "Please Enter a valid contsct number" ,"Error",JOptionPane.ERROR_MESSAGE);
        txtContactNo.setText("");
        
        }
    }//GEN-LAST:event_txtContactNoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgimg;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnSave;
    public static javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    public static javax.swing.JLabel lblNotice;
    public static javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblTime;
    public static javax.swing.JTextField txtAccountType;
    public static javax.swing.JTextField txtAddress;
    private javax.swing.JPasswordField txtComfromPassword;
    public static javax.swing.JTextField txtContactNo;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JPasswordField txtPassword;
    public static javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
