/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import AppLogic.LogicIssueBooks;
import AppLogic.iReportView;
import net.sf.jasperreports.view.JRViewer;
import Source.Validation;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Container;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JRException;
import javax.swing.*;
import java.util.HashMap;
import Source.DBConnection;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.sf.jasperreports.engine.JasperPrint;
/**
 *
 * @author Dhanuka Perera
 */
public class IssueBooks extends javax.swing.JPanel {

    /**
     * Creates new form IssueBooks
     */
     LogicIssueBooks newlogicissuebooks=new LogicIssueBooks();
   
    public IssueBooks() {
        initComponents();
       
        newlogicissuebooks.tableLoad();
        
         if(txtFind.getText()==null)
            newlogicissuebooks.tableLoad();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appBackground = new javax.swing.JPanel();
        btnAdd = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnReports = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbList = new javax.swing.JComboBox<>();
        txtFind = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblFindIcon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDueDate = new javax.swing.JLabel();
        lblBookID = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        lblMemberid = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblIssueDate = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();
        txtBookTitle = new javax.swing.JTextField();
        txtMemberId = new javax.swing.JTextField();
        txtMemberName = new javax.swing.JTextField();
        cmbDay = new javax.swing.JComboBox();
        cmbMonth = new javax.swing.JComboBox();
        cmbYear = new javax.swing.JComboBox();
        cmbDay1 = new javax.swing.JComboBox();
        cmbMonth1 = new javax.swing.JComboBox();
        cmbYear1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIssueBooks = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtfind = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblBookID1 = new javax.swing.JLabel();

        appBackground.setBackground(new java.awt.Color(51, 51, 51));
        appBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                appBackgroundMouseMoved(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/add.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpdateMouseReleased(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteMouseReleased(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear2.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/reports.png"))); // NOI18N
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        cmbList.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IssueBook ID", "Member Id", "Member Name", "Book ID", "Book Title", "Issue Date", "Due Date" }));

        txtFind.setBackground(new java.awt.Color(51, 51, 51));
        txtFind.setFont(new java.awt.Font("Myriad Web Pro", 2, 14)); // NOI18N
        txtFind.setForeground(new java.awt.Color(255, 255, 255));
        txtFind.setText("Find...");
        txtFind.setBorder(null);
        txtFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFindMouseClicked(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        lblFindIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/touch.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFindIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFindIcon)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        lblDueDate.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblDueDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDueDate.setText("Due Date");

        lblBookID.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblBookID.setForeground(new java.awt.Color(255, 255, 255));
        lblBookID.setText("Book ID");

        lblBookName.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblBookName.setForeground(new java.awt.Color(255, 255, 255));
        lblBookName.setText("Book Title");

        lblMemberid.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblMemberid.setForeground(new java.awt.Color(255, 255, 255));
        lblMemberid.setText("Member ID");

        lblName.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Member Name");

        lblIssueDate.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblIssueDate.setForeground(new java.awt.Color(255, 255, 255));
        lblIssueDate.setText("Issue Date");

        txtBookId.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtBookId.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtBookId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBookIdKeyReleased(evt);
            }
        });

        txtBookTitle.setEditable(false);
        txtBookTitle.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtBookTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        txtMemberId.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtMemberId.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtMemberId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberIdKeyReleased(evt);
            }
        });

        txtMemberName.setEditable(false);
        txtMemberName.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtMemberName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtMemberName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberNameKeyReleased(evt);
            }
        });

        cmbDay.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbDay.setForeground(new java.awt.Color(51, 51, 51));
        cmbDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DAY", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        cmbMonth.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbMonth.setForeground(new java.awt.Color(51, 51, 51));
        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONTH", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cmbYear.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbYear.setForeground(new java.awt.Color(51, 51, 51));
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR", "2010", "2011", "2012", "2013", "2014", "2015", "2016", " " }));

        cmbDay1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbDay1.setForeground(new java.awt.Color(51, 51, 51));
        cmbDay1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DAY", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        cmbMonth1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbMonth1.setForeground(new java.awt.Color(51, 51, 51));
        cmbMonth1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONTH", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cmbYear1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbYear1.setForeground(new java.awt.Color(51, 51, 51));
        cmbYear1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBookName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblIssueDate)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMemberid)
                    .addComponent(lblName)
                    .addComponent(lblDueDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(cmbDay1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookID)
                    .addComponent(lblMemberid)
                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBookName)
                        .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIssueDate)
                    .addComponent(lblDueDate)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        tblIssueBooks.setBackground(new java.awt.Color(51, 51, 51));
        tblIssueBooks.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        tblIssueBooks.setForeground(new java.awt.Color(255, 255, 255));
        tblIssueBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblIssueBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIssueBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIssueBooks);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtfind.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtfind.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/paraReport.png"))); // NOI18N
        jLabel1.setText("Generate Report");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        lblBookID1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblBookID1.setForeground(new java.awt.Color(255, 255, 255));
        lblBookID1.setText("Member ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBookID1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblBookID1))
                .addContainerGap())
        );

        javax.swing.GroupLayout appBackgroundLayout = new javax.swing.GroupLayout(appBackground);
        appBackground.setLayout(appBackgroundLayout);
        appBackgroundLayout.setHorizontalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appBackgroundLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReports)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(appBackgroundLayout.createSequentialGroup()
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        appBackgroundLayout.setVerticalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appBackgroundLayout.createSequentialGroup()
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReports)
                            .addComponent(btnClear)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)
                            .addComponent(btnAdd)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
  private void clear()
    {
        txtBookId.setText("");
        txtBookTitle.setText("");
        
        
        txtMemberId.setText("");
        txtMemberName.setText("");
       
        txtFind.setText("Find...");
    }
    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // TODO add your handling code here:
          try {
                 ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/add_hover.png"));
        btnAdd.setIcon(changeIcon);
        } catch (Exception e) {
            //Err
        }
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // TODO add your handling code here:
            try {
                 ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/add.png"));
        btnAdd.setIcon(changeIcon);
        } catch (Exception e) {
            //Err
        }
    }//GEN-LAST:event_btnAddMouseExited

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        // TODO add your handling code here:
            try {
        ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/touch_hover.png"));
        lblFindIcon.setIcon(changeIcon);
        } catch (Exception e) {
            //Err
        }
    }//GEN-LAST:event_txtFindKeyPressed

    private void appBackgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appBackgroundMouseMoved
        // TODO add your handling code here:
              try {
        ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/touch.png"));
        lblFindIcon.setIcon(changeIcon);
        } catch (Exception e) {
            //Err
        }
    }//GEN-LAST:event_appBackgroundMouseMoved

    private void txtFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFindMouseClicked
        // TODO add your handling code here:
        txtFind.setText("");
    }//GEN-LAST:event_txtFindMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        
       if((Validation.isEmpty(txtMemberId.getText()) == false)&&(Validation.isEmpty(txtMemberName.getText()) == false)&&(Validation.isEmpty(txtBookId.getText()) == false)&&(Validation.isEmpty(txtBookTitle.getText()) == false))
       {
          
            newlogicissuebooks.Add(txtMemberId.getText(),txtMemberName.getText(),txtBookId.getText(),txtBookTitle.getText(),cmbDay.getSelectedItem().toString(),cmbMonth.getSelectedItem().toString(),cmbYear.getSelectedItem().toString(),cmbDay1.getSelectedItem().toString(),cmbMonth1.getSelectedItem().toString(),cmbYear1.getSelectedItem().toString());
            newlogicissuebooks.tableLoad();       
         
       }
       else
       {
           JOptionPane.showMessageDialog(null,"Please Fill all the fields","Error",JOptionPane.ERROR_MESSAGE);
       }
       
       clear();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:
                try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit_hover.png"));
           btnUpdate.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
        clear();
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
            try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/edit.png"));
            btnUpdate.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        // TODO add your handling code here:
           try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete_hover.png"));
            btnDelete.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        // TODO add your handling code here:
              try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete.png"));
            btnDelete.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
          try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2_hover.png"));
            btnClear.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
           try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2.png"));
            btnClear.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseEntered
        // TODO add your handling code here:
          try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports_hover.png"));
            btnReports.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnReportsMouseEntered

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        // TODO add your handling code here:
             try 
        {
            ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports.png"));
            btnReports.setIcon(changeIcon);
            
        } catch (Exception e) {
            // Err
        }
    }//GEN-LAST:event_btnReportsMouseExited

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
            clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void tblIssueBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIssueBooksMouseClicked
        // TODO add your handling code here:
               int getSelectedRow = tblIssueBooks.getSelectedRow();
         
     
        String 	MemberId= tblIssueBooks.getValueAt(getSelectedRow, 1).toString();
        String MemberName=tblIssueBooks.getValueAt(getSelectedRow, 2).toString();
        String 	BookID= tblIssueBooks.getValueAt(getSelectedRow, 3).toString();
        String BookTitle= tblIssueBooks.getValueAt(getSelectedRow, 4).toString();
        String IssueDate= tblIssueBooks.getValueAt(getSelectedRow, 5).toString();
        String DueDate= tblIssueBooks.getValueAt(getSelectedRow, 6).toString();
       
       
       txtMemberId.setText(MemberId);
       txtMemberName.setText(MemberName);
       txtBookId.setText(BookID);
       txtBookTitle.setText(BookTitle);
       
       String day = IssueDate.substring(0,2);
       cmbDay.setSelectedItem(day);
       
       String month = IssueDate.substring(3,5);
      cmbMonth.setSelectedItem(month);
       
       String year = IssueDate.substring(6,10);
      cmbYear.setSelectedItem(year);
      
      String day1 = DueDate.substring(0,2);
       cmbDay1.setSelectedItem(day1);
       
       String month1 = DueDate.substring(3,5);
      cmbMonth1.setSelectedItem(month1);
       
       String year1 = DueDate.substring(6,10);
      cmbYear1.setSelectedItem(year1);
       
       
    }//GEN-LAST:event_tblIssueBooksMouseClicked

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        // TODO add your handling code here:
           try{ 
        String filter = cmbList.getSelectedItem().toString();
             String searchItem = txtFind.getText();
             newlogicissuebooks.find(filter,searchItem);
            }
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_txtFindKeyReleased

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddMouseReleased

    private void btnUpdateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnUpdateMouseReleased

    private void btnDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseReleased
        // TODO add your handling code here:
          
    }//GEN-LAST:event_btnDeleteMouseReleased

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
         int msg =  JOptionPane.showConfirmDialog(null,"Do you really want to UPDATE this record?");
        
        if(msg==0)
        {
            int getRowId =  tblIssueBooks.getSelectedRow();
         
            String IssueBookId  =  tblIssueBooks.getValueAt(getRowId, 0).toString();
        
            newlogicissuebooks.updateTable(IssueBookId,txtMemberId.getText(),txtMemberName.getText(),txtBookId.getText(), txtBookTitle.getText(),cmbDay.getSelectedItem().toString(),cmbMonth.getSelectedItem().toString(),cmbYear.getSelectedItem().toString(),cmbDay1.getSelectedItem().toString(),cmbMonth1.getSelectedItem().toString(),cmbYear1.getSelectedItem().toString());
            clear();
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
             int msg = JOptionPane.showConfirmDialog(null, "Do you really want to DELETE this record?");
          //LogicMagazines newmagazines=new LogicMagazines();
        if (msg == 0) 
        {
            int getRowId = tblIssueBooks.getSelectedRow();

            String IssueBookId = tblIssueBooks.getValueAt(getRowId, 0).toString();

           newlogicissuebooks.delete( IssueBookId);
            clear();
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtBookIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookIdKeyReleased
        
        String searchbook = txtBookId.getText();
       
       newlogicissuebooks.findBookTitle(searchbook);
    }//GEN-LAST:event_txtBookIdKeyReleased

    private void txtMemberNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberNameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMemberNameKeyReleased

    private void txtMemberIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberIdKeyReleased
        // TODO add your handling code here:
          String searchMembername = txtMemberId.getText();
       
       newlogicissuebooks.findMembername(searchMembername);
    }//GEN-LAST:event_txtMemberIdKeyReleased

    private void btnReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseClicked
          
       iReportView r = new iReportView( Main.path+ "\\src\\Reports\\IssueBooks.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_btnReportsMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        HashMap para = new HashMap();
        if(txtfind.getText().length() != 0)
        {
            para.put("paraissuememberid",txtfind.getText());
            
             iReportView r = new iReportView( Main.path+ "\\src\\Reports\\paraissuebook.jasper",para);
            r.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Insert Valid Record","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appBackground;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReports;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JComboBox cmbDay;
    private javax.swing.JComboBox cmbDay1;
    private javax.swing.JComboBox<String> cmbList;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox cmbMonth1;
    private javax.swing.JComboBox cmbYear;
    private javax.swing.JComboBox cmbYear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBookID;
    private javax.swing.JLabel lblBookID1;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblFindIcon;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblMemberid;
    private javax.swing.JLabel lblName;
    public static javax.swing.JTable tblIssueBooks;
    private javax.swing.JTextField txtBookId;
    public static javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtMemberId;
    public static javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtfind;
    // End of variables declaration//GEN-END:variables
}
