/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import AppLogic.iReportView;
import AppLogic.logicReturnBooks;
import Source.Validation;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhanuka Perera
 */
public class ReturnBooks extends javax.swing.JPanel {

    logicReturnBooks returnbooks = new logicReturnBooks();
    /**
     * Creates new form ReturnBooks
     */
    public ReturnBooks() {
        initComponents();
        
        returnbooks.tableLoad();
        
        //Find text is null load the table
        if(txtFind.getText()==null)
            returnbooks.tableLoad();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appBackground = new javax.swing.JPanel();
        cmbList = new javax.swing.JComboBox();
        txtFind = new javax.swing.JTextField();
        lblFindIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblBookid = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        lblBookTitle = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblMemberid = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtDueDate = new javax.swing.JTextField();
        lblIssueDate = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        txtBookid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFine = new javax.swing.JLabel();
        cmbMemberID = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReturnBooks = new javax.swing.JTable();
        btnReports = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnAccept = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtfind = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblBookid1 = new javax.swing.JLabel();

        appBackground.setBackground(new java.awt.Color(51, 51, 51));
        appBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                appBackgroundMouseMoved(evt);
            }
        });

        cmbList.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        cmbList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Return Book ID", "Book ID", "Book Title", "Member ID", "Member Name", "Issue Date", "Due Date", "Fine" }));

        txtFind.setBackground(new java.awt.Color(51, 51, 51));
        txtFind.setFont(new java.awt.Font("Myriad Web Pro", 2, 14)); // NOI18N
        txtFind.setForeground(new java.awt.Color(255, 255, 255));
        txtFind.setText("Find...");
        txtFind.setBorder(null);
        txtFind.setOpaque(false);
        txtFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFindMouseClicked(evt);
            }
        });
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
        });

        lblFindIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/touch.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblBookid.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblBookid.setForeground(new java.awt.Color(255, 255, 255));
        lblBookid.setText("Book ID");

        txtBookTitle.setEditable(false);
        txtBookTitle.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtBookTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookTitleActionPerformed(evt);
            }
        });

        lblBookTitle.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblBookTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblBookTitle.setText("Book Title");

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblMemberid.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblMemberid.setForeground(new java.awt.Color(255, 255, 255));
        lblMemberid.setText("Member Id");

        txtIssueDate.setEditable(false);
        txtIssueDate.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtIssueDate.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtIssueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssueDateActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");

        txtDueDate.setEditable(false);
        txtDueDate.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtDueDate.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtDueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDueDateActionPerformed(evt);
            }
        });

        lblIssueDate.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblIssueDate.setForeground(new java.awt.Color(255, 255, 255));
        lblIssueDate.setText("Issue Date");

        lblDueDate.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblDueDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDueDate.setText("Due Date");

        txtBookid.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtBookid.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txtBookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBookidKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fine");

        lblFine.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblFine.setForeground(new java.awt.Color(255, 255, 255));
        lblFine.setText("0.0");

        cmbMemberID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbMemberIDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbMemberIDMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblBookTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMemberid, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                            .addComponent(lblBookid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBookid, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(240, 240, 240))
                    .addComponent(txtIssueDate)
                    .addComponent(txtDueDate))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookid)
                    .addComponent(txtBookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIssueDate)
                    .addComponent(txtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookTitle)
                    .addComponent(lblDueDate)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMemberid)
                        .addComponent(cmbMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblFine)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblReturnBooks.setBackground(new java.awt.Color(51, 51, 51));
        tblReturnBooks.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        tblReturnBooks.setForeground(new java.awt.Color(255, 255, 255));
        tblReturnBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReturnBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReturnBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReturnBooks);

        btnReports.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/reports.png"))); // NOI18N
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear2.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        btnAccept.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Accept.png"))); // NOI18N
        btnAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptMouseExited(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtfind.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        txtfind.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/paraReport.png"))); // NOI18N
        jLabel2.setText("Generate Report");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });

        lblBookid1.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblBookid1.setForeground(new java.awt.Color(255, 255, 255));
        lblBookid1.setText("Member ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBookid1)
                .addGap(33, 33, 33)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblBookid1))
                .addContainerGap())
        );

        javax.swing.GroupLayout appBackgroundLayout = new javax.swing.GroupLayout(appBackground);
        appBackground.setLayout(appBackgroundLayout);
        appBackgroundLayout.setHorizontalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appBackgroundLayout.createSequentialGroup()
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appBackgroundLayout.createSequentialGroup()
                                .addComponent(btnAccept)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReports)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(appBackgroundLayout.createSequentialGroup()
                                        .addComponent(lblFindIcon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1)))
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appBackgroundLayout.createSequentialGroup()
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))))
        );
        appBackgroundLayout.setVerticalGroup(
            appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appBackgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccept)
                    .addGroup(appBackgroundLayout.createSequentialGroup()
                        .addGroup(appBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFindIcon)
                            .addComponent(cmbList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnReports))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

   
    
    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/touch_hover.png"));
             lblFindIcon.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_txtFindKeyPressed

    private void txtFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFindMouseClicked
        txtFind.setText("");
    }//GEN-LAST:event_txtFindMouseClicked

    private void txtDueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDueDateActionPerformed

    private void txtIssueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssueDateActionPerformed

    private void btnAcceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/Accept_hover.png"));
             btnAccept.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnAcceptMouseEntered

    private void btnAcceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseExited
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/Accept.png"));
             btnAccept.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnAcceptMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2_hover.png"));
             btnClear.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/clear2.png"));
             btnClear.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnClearMouseExited

    private void btnReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports_hover.png"));
             btnReports.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnReportsMouseEntered

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/reports.png"));
             btnReports.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnReportsMouseExited

    private void btnAcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseClicked
        String Fine = lblFine.getText();
        Float Fine_Value = Float.parseFloat(Fine);
        
        if((Validation.isEmpty(txtBookid.getText()) == false))
        {
        returnbooks.Add(txtBookid.getText(),txtBookTitle.getText(),cmbMemberID.getSelectedItem().toString(),txtName.getText(),txtIssueDate.getText(),txtDueDate.getText(),Fine_Value);
        returnbooks.tableLoad();
        }
        else
        {
           JOptionPane.showMessageDialog(null,"Please Fill all the fields","Error",JOptionPane.ERROR_MESSAGE);

        }
        returnbooks.clear();
    }//GEN-LAST:event_btnAcceptMouseClicked

    private void txtBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookTitleActionPerformed

    private void appBackgroundMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appBackgroundMouseMoved
       //mouse moved away from the find textbox    
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/touch.png"));
             lblFindIcon.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_appBackgroundMouseMoved

    private void txtBookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookidKeyReleased
       String searchbook = txtBookid.getText();
       
       returnbooks.findbook(searchbook);
    }//GEN-LAST:event_txtBookidKeyReleased

    private void cmbMemberIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMemberIDMouseClicked
       
    }//GEN-LAST:event_cmbMemberIDMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        returnbooks.clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void cmbMemberIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbMemberIDMousePressed
       String memberid = cmbMemberID.getSelectedItem().toString();
       
       returnbooks.findmemberdetails(memberid);
       
       String duedate = txtDueDate.getText();
       returnbooks.calculatefine(duedate);

    }//GEN-LAST:event_cmbMemberIDMousePressed

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        try{ 
        String list = cmbList.getSelectedItem().toString();
             String search = txtFind.getText();
             returnbooks.find(list,search);
            }
            catch(Exception e)
            {
               JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_txtFindKeyReleased

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete_hover.png"));
             btnDelete.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        try 
        {
             ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/delete.png"));
             btnDelete.setIcon(changeIcon);
             
        } 
        catch (Exception e) 
        {
            //err
        }
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        try{ 
            
        int getSelectedRow = tblReturnBooks.getSelectedRow();
        String ReturnID = tblReturnBooks.getValueAt(getSelectedRow,0).toString();
        String 	MemberID= tblReturnBooks.getValueAt(getSelectedRow, 3).toString();
        
         cmbMemberID.setSelectedItem(MemberID);
         returnbooks.delete(ReturnID);
         returnbooks.tableLoad();
       
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Insert Valid Record","Error",JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseClicked
          iReportView r = new iReportView( Main.path+ "\\src\\Reports\\ReturnBooks.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_btnReportsMouseClicked

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        
        
        
    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       
         HashMap para = new HashMap();
         
        if(txtfind.getText().length() != 0)
        {
            para.put("paraissuememberid",txtfind.getText());
            iReportView r = new iReportView( Main.path+ "\\src\\Reports\\parareturnbook.jasper",para);
            r.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Insert Valid Record","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tblReturnBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReturnBooksMouseClicked
      
          int getSelectedRow = tblReturnBooks.getSelectedRow();
         
        String 	BookID= tblReturnBooks.getValueAt(getSelectedRow, 1).toString();
        String BookTitle=tblReturnBooks.getValueAt(getSelectedRow, 2).toString();
        String 	MemberID= tblReturnBooks.getValueAt(getSelectedRow, 3).toString();
        String MemberName= tblReturnBooks.getValueAt(getSelectedRow, 4).toString();
        String IssueDate= tblReturnBooks.getValueAt(getSelectedRow, 5).toString();
        String DueDate= tblReturnBooks.getValueAt(getSelectedRow, 6).toString();
        String Fine= tblReturnBooks.getValueAt(getSelectedRow, 7).toString();
        
       txtBookid.setText(BookID);
       txtBookTitle.setText(BookTitle);
       cmbMemberID.setSelectedItem(MemberID);
       txtName.setText(MemberName);
       txtIssueDate.setText(IssueDate);
       txtDueDate.setText(DueDate);
       lblFine.setText(Fine);
      
      
    }//GEN-LAST:event_tblReturnBooksMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appBackground;
    private javax.swing.JLabel btnAccept;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnReports;
    private javax.swing.JComboBox cmbList;
    public static javax.swing.JComboBox cmbMemberID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBookTitle;
    private javax.swing.JLabel lblBookid;
    private javax.swing.JLabel lblBookid1;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JLabel lblFindIcon;
    public static javax.swing.JLabel lblFine;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblMemberid;
    private javax.swing.JLabel lblName;
    public static javax.swing.JTable tblReturnBooks;
    public static javax.swing.JTextField txtBookTitle;
    public static javax.swing.JTextField txtBookid;
    public static javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtFind;
    public static javax.swing.JTextField txtIssueDate;
    public static javax.swing.JTextField txtName;
    private javax.swing.JTextField txtfind;
    // End of variables declaration//GEN-END:variables
}
