/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import javax.swing.ImageIcon;

/**
 *
 * @author Dhanuka Perera
 */
public class LMSMessageBox extends javax.swing.JFrame {

    int xMousePos ;
    int yMousePos ;
    
    public LMSMessageBox() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Resources/LMS_100x100.png")).getImage());
    }
    
    public LMSMessageBox(int pMsgIcon, String pMessage, int pOp1, int pOp2, String title)
    {
         initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/Resources/LMS_100x100.png")).getImage());
         
        changeIcon(pMsgIcon);
        displayMessage(pMessage);
        btnOption1(pOp1);
        btnOption2(pOp2);
        setTitle(title);
         
    }
    
    final void changeIcon(int iconNo)
    {
        ImageIcon changeIcon;
        
        try {
            switch (iconNo) 
            {
                case 1:
                    changeIcon = new ImageIcon(getClass().getResource("/Resources/Sucess.png"));
                    lblMessageIcon.setIcon(changeIcon);
                    break;
                case 2:
                    changeIcon = new ImageIcon(getClass().getResource("/Resources/Warning.png"));
                    lblMessageIcon.setIcon(changeIcon);
                    break;
                case 3:
                    changeIcon = new ImageIcon(getClass().getResource("/Resources/Fail.png"));
                    lblMessageIcon.setIcon(changeIcon);
                    break;
            }
        } 
        catch (Exception e) 
        {
            // Erorr!
        }
    }
    
    
    final void displayMessage(String Message)
    {
        lblMessage.setText(Message);
    }
    
    final void btnOption1(int op)
    {
        ImageIcon changeIcon;
        try 
        {
            switch(op)
            {
                case 1:
                    changeIcon = new ImageIcon(getClass().getResource("/Resources/okay.png"));
                    btnOpition1.setIcon(changeIcon);
                    break;
                case 2:
                    changeIcon = new ImageIcon(getClass().getResource("/Resources/yes.png"));
                    btnOpition1.setIcon(changeIcon);
                    break;
            }
        } 
        catch (Exception e) 
        {
             // Erorr!
        }
    }

    final void btnOption2(int op)
    {
        ImageIcon changeIcon;
        
        try 
        {
            switch(op)
            {
                case 1:
                    changeIcon = new ImageIcon(getClass().getResource("/Resources/cancel.png"));
                    btnOption2.setIcon(changeIcon);
                    break;
                case 2:
                    changeIcon = new ImageIcon(getClass().getResource("/Resources/no.png"));
                    btnOption2.setIcon(changeIcon);
                    break;
            }
        } 
        catch (Exception e) 
        {
            // Erorr!
        }
        
    }
    
    @Override
   public final void setTitle(String title)
   {
       
       if(title == null)
       {
          lblTitle.setText("Message"); 
       }
       else
       {
           lblTitle.setText(title);
       }
       
      
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlTitleBar = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblMessageIcon = new javax.swing.JLabel();
        btnOption2 = new javax.swing.JLabel();
        btnOpition1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));

        pnlTitleBar.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitleBarMouseDragged(evt);
            }
        });
        pnlTitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitleBarMousePressed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Myriad Web Pro", 0, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LMS.png"))); // NOI18N
        lblTitle.setText("Title");

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(361, 361, 361)
                .addComponent(btnClose)
                .addContainerGap())
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(lblTitle))
                .addContainerGap())
        );

        lblMessage.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Message");

        lblMessageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Warning.png"))); // NOI18N

        btnOption2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/no.png"))); // NOI18N

        btnOpition1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/yes.png"))); // NOI18N

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblMessageIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOpition1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOption2)
                .addGap(103, 103, 103))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMessageIcon)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOpition1)
                    .addComponent(btnOption2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
        ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/close_hover.png"));
        btnClose.setIcon(changeIcon);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void pnlTitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleBarMouseDragged
        int ScreenX =  evt.getXOnScreen();
        int ScreeY = evt.getYOnScreen();

        this.setLocation(ScreenX - xMousePos, ScreeY - yMousePos);
    }//GEN-LAST:event_pnlTitleBarMouseDragged

    private void pnlTitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleBarMousePressed
        xMousePos = evt.getX();
        yMousePos = evt.getY();
    }//GEN-LAST:event_pnlTitleBarMousePressed

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        ImageIcon changeIcon = new ImageIcon(getClass().getResource("/Resources/close.png"));
        btnClose.setIcon(changeIcon);
    }//GEN-LAST:event_btnCloseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LMSMessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LMSMessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LMSMessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LMSMessageBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LMSMessageBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnOpition1;
    private javax.swing.JLabel btnOption2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMessageIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlTitleBar;
    // End of variables declaration//GEN-END:variables
}
